const {chromium}=require('/home/claude/t/node_modules/playwright-core');const fs=require('fs');
const mark=fs.readFileSync('/home/claude/specialme-website/brand/specialme-mark.svg','utf8');
const b64=f=>require('fs').readFileSync(f).toString('base64');const fonts=`@font-face{font-family:B;font-weight:700;src:url(data:font/woff2;base64,${b64('/home/claude/ocr/node_modules/@fontsource/bricolage-grotesque/files/bricolage-grotesque-latin-700-normal.woff2')})}@font-face{font-family:A;font-weight:400;src:url(data:font/woff2;base64,${b64('/home/claude/ocr/node_modules/@fontsource/atkinson-hyperlegible/files/atkinson-hyperlegible-latin-400-normal.woff2')})}`;
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
 for(const [n,s] of [['favicon-32.png',32],['apple-touch-icon.png',180],['icon-192.png',192],['icon-512.png',512]]){
  const p=await b.newPage({viewport:{width:s,height:s}});await p.setContent('<body style="margin:0">'+mark.replace('width="64" height="64"','width="'+s+'" height="'+s+'"')+'</body>');await p.screenshot({path:'/home/claude/specialme-website/'+n,omitBackground:true});await p.close();}
 const p=await b.newPage({viewport:{width:1200,height:630}});
 await p.setContent('<style>'+fonts+'body{margin:0;width:1200px;height:630px;background:#0B3A42;color:#E8F4F6;font-family:A;display:flex;flex-direction:column;justify-content:center;padding:0 90px;box-sizing:border-box}.row{display:flex;align-items:center;gap:28px}.w{font:700 96px B;letter-spacing:-.02em;line-height:1}.w b{color:#5BC8D4}.rule{width:96px;height:6px;background:#F2C14E;border-radius:3px;margin:40px 0 28px}p{font-size:38px;line-height:1.35;margin:0;max-width:1000px;color:#A9C7CD}</style><div class="row">'+fs.readFileSync('/home/claude/specialme-website/brand/specialme-mark-mono-light.svg','utf8').replace('width="64" height="64"','width="132" height="132"')+'<div class="w">Special<b>Me</b></div></div><div class="rule"></div><p>Get your child\'s care out of the binder. Launching soon.</p>');
 await p.evaluate(async()=>{await document.fonts.load('700 96px B');await document.fonts.load('400 38px A');await document.fonts.ready});await p.waitForTimeout(400);await p.screenshot({path:'/home/claude/specialme-website/og-image.png'});await b.close();console.log('ok')})();
